version: '3.8'

services:
  postgres:
    image: postgis/postgis:15-3.3-alpine
    restart: always
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgrespassword
      POSTGRES_USER: postgres
      POSTGRES_DB: enatega
    ports:
      - "5432:5432"

  graphql-engine:
    image: hasura/graphql-engine:v2.33.0
    ports:
      - "8080:8080"
    restart: always
    environment:
      HASURA_GRAPHQL_DATABASE_URL: postgres://postgres:postgrespassword@postgres:5432/enatega
      HASURA_GRAPHQL_ENABLE_CONSOLE: "true" # set to "false" to disable console
      HASURA_GRAPHQL_DEV_MODE: "true"
      HASURA_GRAPHQL_ENABLED_LOG_TYPES: startup, http-log, webhook-log, websocket-log, query-log
      ## uncomment next line to set an admin secret
      # HASURA_GRAPHQL_ADMIN_SECRET: myadminsecretkey

  fastapi-service:
    build: ./fastapi
    ports:
      - "8000:8000"
    volumes:
      - ./fastapi:/app
    environment:
      - HASURA_GRAPHQL_URL=http://graphql-engine:8080/v1/graphql
      - DATABASE_URL=postgres://postgres:postgrespassword@postgres:5432/enatega
    depends_on:
      - graphql-engine

volumes:
  db_data:
